// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reserve/vaults/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VaultStatus is the status of a vault.
type VaultStatus int32

const (
	// ACTIVE - vault is in use and can be changed
	ACTIVE VaultStatus = 0
	// LIQUIDATING - vault is being liquidated by the vault manager, and cannot be
	// changed by the user. If liquidation fails, vaults may remain in this state.
	// An upgrade might be able to recover them.
	LIQUIDATING VaultStatus = 1
	// TRANSFER - vault is able to be transferred (payments and debits frozen
	// until it has a new owner)
	TRANSFER VaultStatus = 2
	// CLOSED - vault was closed by the user and all assets have been paid out
	CLOSED VaultStatus = 3
	// LIQUIDATED - vault was closed by the manager, with remaining assets paid to
	// owner
	LIQUIDATED VaultStatus = 4
)

var VaultStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "LIQUIDATING",
	2: "TRANSFER",
	3: "CLOSED",
	4: "LIQUIDATED",
}

var VaultStatus_value = map[string]int32{
	"ACTIVE":      0,
	"LIQUIDATING": 1,
	"TRANSFER":    2,
	"CLOSED":      3,
	"LIQUIDATED":  4,
}

func (x VaultStatus) String() string {
	return proto.EnumName(VaultStatus_name, int32(x))
}

func (VaultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{0}
}

// Params defines the parameters for the module.
type Params struct {
	MinInitialDebt   cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=min_initial_debt,json=minInitialDebt,proto3,customtype=cosmossdk.io/math.Int" json:"min_initial_debt"`
	AllowedMintDenom []string              `protobuf:"bytes,2,rep,name=allowed_mint_denom,json=allowedMintDenom,proto3" json:"allowed_mint_denom,omitempty"`
	ChargingPeriod   time.Duration         `protobuf:"bytes,3,opt,name=charging_period,json=chargingPeriod,proto3,stdduration" json:"charging_period"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAllowedMintDenom() []string {
	if m != nil {
		return m.AllowedMintDenom
	}
	return nil
}

func (m *Params) GetChargingPeriod() time.Duration {
	if m != nil {
		return m.ChargingPeriod
	}
	return 0
}

// VaultParams defines the parameters for each collateral vault type.
type VaultManagerParams struct {
	MintDenom          string                      `protobuf:"bytes,1,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty"`
	MintSymbol         string                      `protobuf:"bytes,2,opt,name=mint_symbol,json=mintSymbol,proto3" json:"mint_symbol,omitempty"`
	MinCollateralRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=min_collateral_ratio,json=minCollateralRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_collateral_ratio"`
	LiquidationRatio   cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=liquidation_ratio,json=liquidationRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_ratio"`
	MaxDebt            cosmossdk_io_math.Int       `protobuf:"bytes,5,opt,name=max_debt,json=maxDebt,proto3,customtype=cosmossdk.io/math.Int" json:"max_debt"`
	StabilityFee       cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=stability_fee,json=stabilityFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"stability_fee"`
	LiquidationPenalty cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=liquidation_penalty,json=liquidationPenalty,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_penalty"`
	MintingFee         cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=minting_fee,json=mintingFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"minting_fee"`
}

func (m *VaultManagerParams) Reset()         { *m = VaultManagerParams{} }
func (m *VaultManagerParams) String() string { return proto.CompactTextString(m) }
func (*VaultManagerParams) ProtoMessage()    {}
func (*VaultManagerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{1}
}
func (m *VaultManagerParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultManagerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VaultManagerParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VaultManagerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultManagerParams.Merge(m, src)
}
func (m *VaultManagerParams) XXX_Size() int {
	return m.Size()
}
func (m *VaultManagerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultManagerParams.DiscardUnknown(m)
}

var xxx_messageInfo_VaultManagerParams proto.InternalMessageInfo

func (m *VaultManagerParams) GetMintDenom() string {
	if m != nil {
		return m.MintDenom
	}
	return ""
}

func (m *VaultManagerParams) GetMintSymbol() string {
	if m != nil {
		return m.MintSymbol
	}
	return ""
}

// VaultManager defines the manager of each collateral vault type.
type VaultManager struct {
	Params        VaultManagerParams    `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Denom         string                `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Symbol        string                `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MintAvailable cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=mint_available,json=mintAvailable,proto3,customtype=cosmossdk.io/math.Int" json:"mint_available"`
}

func (m *VaultManager) Reset()         { *m = VaultManager{} }
func (m *VaultManager) String() string { return proto.CompactTextString(m) }
func (*VaultManager) ProtoMessage()    {}
func (*VaultManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{2}
}
func (m *VaultManager) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VaultManager.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VaultManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultManager.Merge(m, src)
}
func (m *VaultManager) XXX_Size() int {
	return m.Size()
}
func (m *VaultManager) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultManager.DiscardUnknown(m)
}

var xxx_messageInfo_VaultManager proto.InternalMessageInfo

func (m *VaultManager) GetParams() VaultManagerParams {
	if m != nil {
		return m.Params
	}
	return VaultManagerParams{}
}

func (m *VaultManager) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *VaultManager) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type Vault struct {
	Id               uint64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner            string                      `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Debt             types.Coin                  `protobuf:"bytes,3,opt,name=debt,proto3" json:"debt"`
	CollateralLocked types.Coin                  `protobuf:"bytes,4,opt,name=collateral_locked,json=collateralLocked,proto3" json:"collateral_locked"`
	Status           VaultStatus                 `protobuf:"varint,5,opt,name=status,proto3,enum=reserve.vaults.VaultStatus" json:"status,omitempty"`
	LiquidationPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=liquidation_price,json=liquidationPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidation_price"`
	Address          string                      `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *Vault) Reset()         { *m = Vault{} }
func (m *Vault) String() string { return proto.CompactTextString(m) }
func (*Vault) ProtoMessage()    {}
func (*Vault) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{3}
}
func (m *Vault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vault.Merge(m, src)
}
func (m *Vault) XXX_Size() int {
	return m.Size()
}
func (m *Vault) XXX_DiscardUnknown() {
	xxx_messageInfo_Vault.DiscardUnknown(m)
}

var xxx_messageInfo_Vault proto.InternalMessageInfo

func (m *Vault) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vault) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Vault) GetDebt() types.Coin {
	if m != nil {
		return m.Debt
	}
	return types.Coin{}
}

func (m *Vault) GetCollateralLocked() types.Coin {
	if m != nil {
		return m.CollateralLocked
	}
	return types.Coin{}
}

func (m *Vault) GetStatus() VaultStatus {
	if m != nil {
		return m.Status
	}
	return ACTIVE
}

func (m *Vault) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type VaultLiquidationStatus struct {
	Sold             types.Coin `protobuf:"bytes,4,opt,name=sold,proto3" json:"sold"`
	RemainCollateral types.Coin `protobuf:"bytes,5,opt,name=remain_collateral,json=remainCollateral,proto3" json:"remain_collateral"`
}

func (m *VaultLiquidationStatus) Reset()         { *m = VaultLiquidationStatus{} }
func (m *VaultLiquidationStatus) String() string { return proto.CompactTextString(m) }
func (*VaultLiquidationStatus) ProtoMessage()    {}
func (*VaultLiquidationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{4}
}
func (m *VaultLiquidationStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultLiquidationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VaultLiquidationStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VaultLiquidationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultLiquidationStatus.Merge(m, src)
}
func (m *VaultLiquidationStatus) XXX_Size() int {
	return m.Size()
}
func (m *VaultLiquidationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultLiquidationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VaultLiquidationStatus proto.InternalMessageInfo

func (m *VaultLiquidationStatus) GetSold() types.Coin {
	if m != nil {
		return m.Sold
	}
	return types.Coin{}
}

func (m *VaultLiquidationStatus) GetRemainCollateral() types.Coin {
	if m != nil {
		return m.RemainCollateral
	}
	return types.Coin{}
}

type Liquidation struct {
	DebtDenom              string                             `protobuf:"bytes,1,opt,name=debt_denom,json=debtDenom,proto3" json:"debt_denom,omitempty"`
	MintDenom              string                             `protobuf:"bytes,2,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty"`
	LiquidatingVaults      []*Vault                           `protobuf:"bytes,3,rep,name=liquidating_vaults,json=liquidatingVaults,proto3" json:"liquidating_vaults,omitempty"`
	VaultLiquidationStatus map[uint64]*VaultLiquidationStatus `protobuf:"bytes,4,rep,name=vault_liquidation_status,json=vaultLiquidationStatus,proto3" json:"vault_liquidation_status,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Liquidation) Reset()         { *m = Liquidation{} }
func (m *Liquidation) String() string { return proto.CompactTextString(m) }
func (*Liquidation) ProtoMessage()    {}
func (*Liquidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{5}
}
func (m *Liquidation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Liquidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Liquidation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Liquidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Liquidation.Merge(m, src)
}
func (m *Liquidation) XXX_Size() int {
	return m.Size()
}
func (m *Liquidation) XXX_DiscardUnknown() {
	xxx_messageInfo_Liquidation.DiscardUnknown(m)
}

var xxx_messageInfo_Liquidation proto.InternalMessageInfo

func (m *Liquidation) GetDebtDenom() string {
	if m != nil {
		return m.DebtDenom
	}
	return ""
}

func (m *Liquidation) GetMintDenom() string {
	if m != nil {
		return m.MintDenom
	}
	return ""
}

func (m *Liquidation) GetLiquidatingVaults() []*Vault {
	if m != nil {
		return m.LiquidatingVaults
	}
	return nil
}

func (m *Liquidation) GetVaultLiquidationStatus() map[uint64]*VaultLiquidationStatus {
	if m != nil {
		return m.VaultLiquidationStatus
	}
	return nil
}

type LastUpdate struct {
	Time time.Time `protobuf:"bytes,1,opt,name=time,proto3,stdtime" json:"time"`
}

func (m *LastUpdate) Reset()         { *m = LastUpdate{} }
func (m *LastUpdate) String() string { return proto.CompactTextString(m) }
func (*LastUpdate) ProtoMessage()    {}
func (*LastUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f12ab0d072f9f7c, []int{6}
}
func (m *LastUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LastUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LastUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LastUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastUpdate.Merge(m, src)
}
func (m *LastUpdate) XXX_Size() int {
	return m.Size()
}
func (m *LastUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_LastUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_LastUpdate proto.InternalMessageInfo

func (m *LastUpdate) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func init() {
	proto.RegisterEnum("reserve.vaults.VaultStatus", VaultStatus_name, VaultStatus_value)
	proto.RegisterType((*Params)(nil), "reserve.vaults.Params")
	proto.RegisterType((*VaultManagerParams)(nil), "reserve.vaults.VaultManagerParams")
	proto.RegisterType((*VaultManager)(nil), "reserve.vaults.VaultManager")
	proto.RegisterType((*Vault)(nil), "reserve.vaults.Vault")
	proto.RegisterType((*VaultLiquidationStatus)(nil), "reserve.vaults.VaultLiquidationStatus")
	proto.RegisterType((*Liquidation)(nil), "reserve.vaults.Liquidation")
	proto.RegisterMapType((map[uint64]*VaultLiquidationStatus)(nil), "reserve.vaults.Liquidation.VaultLiquidationStatusEntry")
	proto.RegisterType((*LastUpdate)(nil), "reserve.vaults.LastUpdate")
}

func init() { proto.RegisterFile("reserve/vaults/params.proto", fileDescriptor_1f12ab0d072f9f7c) }

var fileDescriptor_1f12ab0d072f9f7c = []byte{
	// 1112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcb, 0x6f, 0x1b, 0x45,
	0x18, 0xf7, 0xfa, 0xd5, 0xe6, 0x73, 0xe2, 0x3a, 0x43, 0x1a, 0x5c, 0x47, 0xd8, 0x96, 0x0f, 0x28,
	0x8a, 0xe8, 0x2e, 0x75, 0x25, 0xa8, 0x2a, 0x38, 0xc4, 0xb1, 0x83, 0xac, 0xba, 0x25, 0xd9, 0xa4,
	0xad, 0x54, 0x0e, 0xd6, 0x78, 0x77, 0xba, 0x19, 0x65, 0x77, 0xc7, 0xd9, 0x1d, 0xbb, 0xf1, 0x5f,
	0x00, 0xca, 0x85, 0x1e, 0xb9, 0x44, 0xe2, 0x21, 0x24, 0x8e, 0x3d, 0xf4, 0x8f, 0xe8, 0xb1, 0xea,
	0x09, 0x21, 0x54, 0x50, 0x72, 0x28, 0xff, 0x01, 0x57, 0xb4, 0x33, 0xb3, 0xc9, 0xe6, 0x01, 0x6a,
	0xc9, 0xc5, 0xf2, 0x7c, 0x8f, 0xdf, 0x7c, 0xdf, 0xef, 0x7b, 0xec, 0xc0, 0x42, 0x40, 0x42, 0x12,
	0x8c, 0x89, 0x31, 0xc6, 0x23, 0x97, 0x87, 0xc6, 0x10, 0x07, 0xd8, 0x0b, 0xf5, 0x61, 0xc0, 0x38,
	0x43, 0x45, 0xa5, 0xd4, 0xa5, 0xb2, 0x32, 0xe7, 0x30, 0x87, 0x09, 0x95, 0x11, 0xfd, 0x93, 0x56,
	0x95, 0x59, 0xec, 0x51, 0x9f, 0x19, 0xe2, 0x57, 0x89, 0xaa, 0x16, 0x0b, 0x3d, 0x16, 0x1a, 0x03,
	0x1c, 0x12, 0x63, 0x7c, 0x63, 0x40, 0x38, 0xbe, 0x61, 0x58, 0x8c, 0xfa, 0x4a, 0x7f, 0x4d, 0xea,
	0xfb, 0x12, 0x4b, 0x1e, 0x62, 0x57, 0x87, 0x31, 0xc7, 0x25, 0x86, 0x38, 0x0d, 0x46, 0x8f, 0x0d,
	0x7b, 0x14, 0x60, 0x4e, 0x59, 0xec, 0x5a, 0x3b, 0xad, 0xe7, 0xd4, 0x23, 0x21, 0xc7, 0xde, 0x50,
	0x1a, 0x34, 0xbe, 0x4e, 0x43, 0x7e, 0x4d, 0x64, 0x81, 0x1e, 0x41, 0xc9, 0xa3, 0x7e, 0x9f, 0xfa,
	0x94, 0x53, 0xec, 0xf6, 0x6d, 0x32, 0xe0, 0x65, 0xad, 0xae, 0x2d, 0x4e, 0xb5, 0x3e, 0x7e, 0xf1,
	0xba, 0x96, 0xfa, 0xed, 0x75, 0xed, 0xaa, 0xbc, 0x3b, 0xb4, 0xb7, 0x75, 0xca, 0x0c, 0x0f, 0xf3,
	0x2d, 0xbd, 0xeb, 0xf3, 0x57, 0xcf, 0xaf, 0x83, 0x0a, 0xaa, 0xeb, 0xf3, 0x5f, 0xde, 0x3c, 0x5b,
	0xd2, 0xcc, 0xa2, 0x47, 0xfd, 0xae, 0x04, 0x6a, 0x93, 0x01, 0x47, 0x1f, 0x01, 0xc2, 0xae, 0xcb,
	0x9e, 0x10, 0xbb, 0xef, 0x51, 0x9f, 0xf7, 0x6d, 0xe2, 0x33, 0xaf, 0x9c, 0xae, 0x67, 0x16, 0xa7,
	0xcc, 0x92, 0xd2, 0xdc, 0xa5, 0x3e, 0x6f, 0x47, 0x72, 0xb4, 0x0e, 0x57, 0xac, 0x2d, 0x1c, 0x38,
	0xd4, 0x77, 0xfa, 0x43, 0x12, 0x50, 0x66, 0x97, 0x33, 0x75, 0x6d, 0xb1, 0xd0, 0xbc, 0xa6, 0xcb,
	0x7c, 0xf4, 0x38, 0x1f, 0xbd, 0xad, 0xf2, 0x6d, 0xcd, 0x44, 0x31, 0x7e, 0xf7, 0x47, 0x4d, 0x53,
	0x01, 0xc4, 0x00, 0x6b, 0xc2, 0xff, 0x76, 0xfd, 0xaf, 0xef, 0x6b, 0xda, 0xde, 0x9b, 0x67, 0x4b,
	0xef, 0xc7, 0x25, 0xdc, 0x8d, 0x8b, 0x28, 0xd3, 0x6f, 0x7c, 0x9b, 0x03, 0xf4, 0x20, 0x92, 0xdc,
	0xc5, 0x3e, 0x76, 0x48, 0xa0, 0x58, 0xf9, 0x00, 0x20, 0x11, 0xb1, 0xe0, 0xc3, 0x9c, 0xf2, 0x8e,
	0x42, 0xad, 0x41, 0x41, 0xa8, 0xc3, 0x89, 0x37, 0x60, 0x6e, 0x39, 0x2d, 0xf4, 0xc2, 0x63, 0x43,
	0x48, 0xd0, 0x16, 0xcc, 0x45, 0xac, 0x5a, 0xcc, 0x75, 0x31, 0x27, 0x01, 0x76, 0xfb, 0x22, 0x60,
	0x91, 0xd0, 0x54, 0xeb, 0x13, 0xc5, 0xec, 0xc2, 0x59, 0x66, 0x7b, 0xc4, 0xc1, 0xd6, 0xa4, 0x4d,
	0xac, 0x04, 0xbf, 0x6d, 0x62, 0xc9, 0xf4, 0x90, 0x47, 0xfd, 0x95, 0x23, 0x48, 0x33, 0x42, 0x44,
	0x16, 0xcc, 0xba, 0x74, 0x67, 0x44, 0x6d, 0x41, 0x88, 0xba, 0x26, 0x7b, 0xa1, 0x6b, 0x4a, 0x09,
	0x40, 0x79, 0xc9, 0x1d, 0xb8, 0xec, 0xe1, 0x5d, 0xd9, 0x1c, 0xb9, 0xff, 0xd9, 0x1c, 0x97, 0x3c,
	0xbc, 0x2b, 0xba, 0xe2, 0x2b, 0x98, 0x09, 0x39, 0x1e, 0x50, 0x97, 0xf2, 0x49, 0xff, 0x31, 0x21,
	0xe5, 0xfc, 0x85, 0xa2, 0x9d, 0x3e, 0x02, 0x5b, 0x25, 0x04, 0x39, 0xf0, 0x5e, 0x92, 0x8e, 0x21,
	0xf1, 0xb1, 0xcb, 0x27, 0xe5, 0x4b, 0x17, 0xe3, 0x3d, 0x01, 0xb9, 0x26, 0x11, 0xd1, 0x43, 0xd9,
	0x02, 0x51, 0xb3, 0x46, 0x39, 0x5c, 0xbe, 0xd0, 0x05, 0xa0, 0xa0, 0x56, 0x09, 0x69, 0xfc, 0xae,
	0xc1, 0x74, 0xb2, 0x23, 0x51, 0x07, 0xf2, 0x72, 0xe3, 0x88, 0x3e, 0x2c, 0x34, 0x1b, 0xfa, 0xc9,
	0x95, 0xa3, 0x9f, 0xed, 0xdf, 0xd6, 0x54, 0x14, 0x88, 0xc4, 0x56, 0xce, 0x68, 0x0e, 0x72, 0xf1,
	0xfc, 0x45, 0xdd, 0x2a, 0x0f, 0x68, 0x1e, 0xf2, 0xaa, 0x89, 0x45, 0x6b, 0x9a, 0xea, 0x84, 0x1e,
	0x42, 0x51, 0x74, 0x38, 0x1e, 0x63, 0xea, 0xe2, 0x81, 0x4b, 0x54, 0x4f, 0xbd, 0x7b, 0xdd, 0x67,
	0x22, 0x9c, 0xe5, 0x18, 0xa6, 0xf1, 0x63, 0x06, 0x72, 0x22, 0x60, 0x54, 0x84, 0x34, 0xb5, 0x45,
	0x4e, 0x59, 0x33, 0x4d, 0x6d, 0xa4, 0x43, 0x8e, 0x3d, 0xf1, 0x49, 0x20, 0x03, 0x6c, 0x95, 0x5f,
	0x3d, 0xbf, 0x3e, 0xa7, 0xc0, 0x96, 0x6d, 0x3b, 0x20, 0x61, 0xb8, 0xc1, 0x03, 0xea, 0x3b, 0xa6,
	0x34, 0x43, 0xb7, 0x20, 0x2b, 0x1a, 0x32, 0x5e, 0x12, 0xca, 0x36, 0xda, 0xa7, 0xba, 0xda, 0xa7,
	0xfa, 0x0a, 0xa3, 0x7e, 0x92, 0x0c, 0xe1, 0x81, 0xd6, 0x61, 0x36, 0x31, 0x99, 0x2e, 0xb3, 0xb6,
	0x89, 0x2d, 0xf2, 0x7b, 0x5b, 0x98, 0xd2, 0xb1, 0x7b, 0x4f, 0x78, 0xa3, 0x9b, 0x90, 0x0f, 0x39,
	0xe6, 0xa3, 0x50, 0xcc, 0x47, 0xb1, 0xb9, 0x70, 0x6e, 0x91, 0x36, 0x84, 0x89, 0xa9, 0x4c, 0x4f,
	0xcf, 0xee, 0x30, 0xa0, 0xd6, 0x45, 0xa7, 0x21, 0x39, 0xbb, 0x6b, 0x11, 0x1e, 0x6a, 0xc2, 0x25,
	0x2c, 0xe9, 0x53, 0x53, 0xf0, 0xef, 0xc4, 0xc6, 0x86, 0x8d, 0x9f, 0x35, 0x98, 0x17, 0x01, 0xf7,
	0x8e, 0xd1, 0x64, 0xec, 0x11, 0xeb, 0x21, 0x73, 0xdf, 0x8d, 0x2e, 0xe1, 0x11, 0xb1, 0x1e, 0x10,
	0x0f, 0x9f, 0x58, 0x8b, 0x82, 0xad, 0xb7, 0x66, 0x5d, 0xba, 0x1f, 0x6f, 0xc0, 0xc6, 0xdf, 0x69,
	0x28, 0x24, 0x42, 0x8c, 0xd6, 0x76, 0x54, 0xe0, 0x93, 0x6b, 0x3b, 0x92, 0xc8, 0xb5, 0x7d, 0x72,
	0xab, 0xa7, 0x4f, 0x6f, 0xf5, 0x36, 0x1c, 0x0f, 0xba, 0xef, 0xf4, 0x65, 0xe1, 0xca, 0x99, 0x7a,
	0x66, 0xb1, 0xd0, 0xbc, 0x7a, 0x6e, 0x3d, 0xcd, 0xd9, 0x84, 0x83, 0x90, 0x84, 0x68, 0x07, 0xca,
	0xc2, 0xa4, 0x9f, 0x2c, 0xad, 0xea, 0x8d, 0xac, 0xc0, 0xfa, 0xf4, 0x34, 0x56, 0x22, 0x05, 0xfd,
	0x7c, 0xda, 0x3b, 0x3e, 0x0f, 0x26, 0xe6, 0xfc, 0xf8, 0x5c, 0x65, 0x65, 0x07, 0x16, 0xfe, 0xc3,
	0x0d, 0x95, 0x20, 0xb3, 0x4d, 0x26, 0x6a, 0xd2, 0xa2, 0xbf, 0xe8, 0x33, 0xc8, 0x8d, 0xb1, 0x3b,
	0x22, 0x82, 0x83, 0x42, 0xf3, 0xc3, 0x73, 0x93, 0x3b, 0x83, 0x66, 0x4a, 0xa7, 0xdb, 0xe9, 0x5b,
	0x5a, 0xe3, 0x0e, 0x40, 0x0f, 0x87, 0xfc, 0xfe, 0xd0, 0xc6, 0x9c, 0xa0, 0xcf, 0x21, 0x1b, 0x3d,
	0x31, 0xd4, 0x82, 0xaa, 0x9c, 0xf9, 0x5e, 0x6f, 0xc6, 0xef, 0x0f, 0xf9, 0xc1, 0x7e, 0x7a, 0xf4,
	0xc1, 0x16, 0x6e, 0x4b, 0x3f, 0x68, 0x50, 0x48, 0xcc, 0x47, 0xb4, 0x94, 0x96, 0x57, 0x36, 0xbb,
	0x0f, 0x3a, 0xa5, 0x54, 0x05, 0xf6, 0xf6, 0xeb, 0xea, 0x84, 0xea, 0x50, 0xe8, 0x75, 0xd7, 0xef,
	0x77, 0xdb, 0xcb, 0x9b, 0xdd, 0x7b, 0x5f, 0x94, 0xb4, 0xca, 0x95, 0xbd, 0xfd, 0x7a, 0x52, 0x84,
	0x2a, 0x70, 0x79, 0xd3, 0x5c, 0xbe, 0xb7, 0xb1, 0xda, 0x31, 0x4b, 0xe9, 0xca, 0xf4, 0xde, 0x7e,
	0xfd, 0xe8, 0x1c, 0xa1, 0xae, 0xf4, 0xbe, 0xdc, 0xe8, 0xb4, 0x4b, 0x19, 0x89, 0x2a, 0x4f, 0xa8,
	0x0a, 0x10, 0x43, 0x74, 0xda, 0xa5, 0x6c, 0xa5, 0xb8, 0xb7, 0x5f, 0x4f, 0x48, 0x2a, 0xd9, 0x6f,
	0x7e, 0xaa, 0xa6, 0x5a, 0xdd, 0x17, 0x07, 0x55, 0xed, 0xe5, 0x41, 0x55, 0xfb, 0xf3, 0xa0, 0xaa,
	0x3d, 0x3d, 0xac, 0xa6, 0x5e, 0x1e, 0x56, 0x53, 0xbf, 0x1e, 0x56, 0x53, 0x8f, 0x0c, 0x87, 0xf2,
	0xad, 0xd1, 0x40, 0xb7, 0x98, 0x67, 0x30, 0x9f, 0x79, 0x13, 0x91, 0xb6, 0xc5, 0x5c, 0xe3, 0xcc,
	0xa3, 0x83, 0x4f, 0x86, 0x24, 0x1c, 0xe4, 0x85, 0xc1, 0xcd, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0x4d, 0xc5, 0xb5, 0x58, 0x0a, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinInitialDebt.Equal(that1.MinInitialDebt) {
		return false
	}
	if len(this.AllowedMintDenom) != len(that1.AllowedMintDenom) {
		return false
	}
	for i := range this.AllowedMintDenom {
		if this.AllowedMintDenom[i] != that1.AllowedMintDenom[i] {
			return false
		}
	}
	if this.ChargingPeriod != that1.ChargingPeriod {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ChargingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChargingPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	if len(m.AllowedMintDenom) > 0 {
		for iNdEx := len(m.AllowedMintDenom) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedMintDenom[iNdEx])
			copy(dAtA[i:], m.AllowedMintDenom[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AllowedMintDenom[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size := m.MinInitialDebt.Size()
		i -= size
		if _, err := m.MinInitialDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VaultManagerParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultManagerParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultManagerParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MintingFee.Size()
		i -= size
		if _, err := m.MintingFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.LiquidationPenalty.Size()
		i -= size
		if _, err := m.LiquidationPenalty.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.StabilityFee.Size()
		i -= size
		if _, err := m.StabilityFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MaxDebt.Size()
		i -= size
		if _, err := m.MaxDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.LiquidationRatio.Size()
		i -= size
		if _, err := m.LiquidationRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinCollateralRatio.Size()
		i -= size
		if _, err := m.MinCollateralRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.MintSymbol) > 0 {
		i -= len(m.MintSymbol)
		copy(dAtA[i:], m.MintSymbol)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MintSymbol)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MintDenom) > 0 {
		i -= len(m.MintDenom)
		copy(dAtA[i:], m.MintDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MintDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VaultManager) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultManager) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultManager) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MintAvailable.Size()
		i -= size
		if _, err := m.MintAvailable.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Vault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.LiquidationPrice.Size()
		i -= size
		if _, err := m.LiquidationPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Status != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.CollateralLocked.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Debt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VaultLiquidationStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultLiquidationStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultLiquidationStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RemainCollateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Sold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	return len(dAtA) - i, nil
}

func (m *Liquidation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Liquidation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Liquidation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VaultLiquidationStatus) > 0 {
		for k := range m.VaultLiquidationStatus {
			v := m.VaultLiquidationStatus[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintParams(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintParams(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintParams(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.LiquidatingVaults) > 0 {
		for iNdEx := len(m.LiquidatingVaults) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidatingVaults[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MintDenom) > 0 {
		i -= len(m.MintDenom)
		copy(dAtA[i:], m.MintDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MintDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DebtDenom) > 0 {
		i -= len(m.DebtDenom)
		copy(dAtA[i:], m.DebtDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DebtDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LastUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LastUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LastUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n8, err8 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err8 != nil {
		return 0, err8
	}
	i -= n8
	i = encodeVarintParams(dAtA, i, uint64(n8))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinInitialDebt.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.AllowedMintDenom) > 0 {
		for _, s := range m.AllowedMintDenom {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChargingPeriod)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *VaultManagerParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MintDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MintSymbol)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.MinCollateralRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.LiquidationRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDebt.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.StabilityFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.LiquidationPenalty.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MintingFee.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *VaultManager) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.MintAvailable.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Vault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovParams(uint64(m.Id))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.Debt.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.CollateralLocked.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.Status != 0 {
		n += 1 + sovParams(uint64(m.Status))
	}
	l = m.LiquidationPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *VaultLiquidationStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Sold.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.RemainCollateral.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Liquidation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DebtDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MintDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.LiquidatingVaults) > 0 {
		for _, e := range m.LiquidatingVaults {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.VaultLiquidationStatus) > 0 {
		for k, v := range m.VaultLiquidationStatus {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovParams(uint64(l))
			}
			mapEntrySize := 1 + sovParams(uint64(k)) + l
			n += mapEntrySize + 1 + sovParams(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *LastUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInitialDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinInitialDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedMintDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedMintDenom = append(m.AllowedMintDenom, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ChargingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultManagerParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultManagerParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultManagerParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintSymbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintSymbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinCollateralRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidationRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StabilityFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StabilityFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationPenalty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidationPenalty.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintingFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultManager) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultManager: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultManager: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintAvailable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintAvailable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Debt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Debt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralLocked", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralLocked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= VaultStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidationPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultLiquidationStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultLiquidationStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultLiquidationStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainCollateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainCollateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Liquidation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Liquidation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Liquidation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DebtDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidatingVaults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidatingVaults = append(m.LiquidatingVaults, &Vault{})
			if err := m.LiquidatingVaults[len(m.LiquidatingVaults)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultLiquidationStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VaultLiquidationStatus == nil {
				m.VaultLiquidationStatus = make(map[uint64]*VaultLiquidationStatus)
			}
			var mapkey uint64
			var mapvalue *VaultLiquidationStatus
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthParams
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthParams
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &VaultLiquidationStatus{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipParams(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthParams
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.VaultLiquidationStatus[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LastUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LastUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LastUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
