// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reserve/psm/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	LimitTotal           cosmossdk_io_math.Int       `protobuf:"bytes,1,opt,name=limit_total,json=limitTotal,proto3,customtype=cosmossdk.io/math.Int" json:"limit_total"`
	AcceptablePriceRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=acceptable_price_ratio,json=acceptablePriceRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"acceptable_price_ratio"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e516259d7293aa1e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "reserve.psm.v1.Params")
}

func init() { proto.RegisterFile("reserve/psm/v1/params.proto", fileDescriptor_e516259d7293aa1e) }

var fileDescriptor_e516259d7293aa1e = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd0, 0xb1, 0x4a, 0x03, 0x31,
	0x18, 0x07, 0xf0, 0x8b, 0x43, 0x87, 0x28, 0x82, 0xa5, 0x4a, 0x6d, 0x21, 0x15, 0x27, 0x11, 0x4d,
	0x2c, 0xbe, 0x41, 0x29, 0x42, 0xc1, 0xa1, 0x16, 0x27, 0x97, 0x23, 0x8d, 0xe1, 0x1a, 0xbc, 0xdc,
	0x17, 0x92, 0x58, 0xec, 0x5b, 0xf8, 0x18, 0x8e, 0x0e, 0x3e, 0x82, 0x43, 0xc7, 0xe2, 0x24, 0x0e,
	0x45, 0xee, 0x06, 0x5f, 0x43, 0x2e, 0x77, 0xa2, 0xe0, 0x12, 0xbe, 0xe4, 0x9f, 0xfc, 0x3e, 0xf2,
	0xe1, 0xae, 0x95, 0x4e, 0xda, 0xb9, 0x64, 0xc6, 0x69, 0x36, 0xef, 0x33, 0xc3, 0x2d, 0xd7, 0x8e,
	0x1a, 0x0b, 0x1e, 0x9a, 0xdb, 0x75, 0x48, 0x8d, 0xd3, 0x74, 0xde, 0xef, 0xec, 0x70, 0xad, 0x32,
	0x60, 0x61, 0xad, 0xae, 0x74, 0x5a, 0x09, 0x24, 0x10, 0x4a, 0x56, 0x56, 0xf5, 0xe9, 0xbe, 0x00,
	0xa7, 0xc1, 0xc5, 0x55, 0x50, 0x6d, 0xaa, 0xe8, 0xf0, 0x15, 0xe1, 0xc6, 0x38, 0x34, 0x69, 0x5e,
	0xe1, 0xcd, 0x54, 0x69, 0xe5, 0x63, 0x0f, 0x9e, 0xa7, 0x6d, 0x74, 0x80, 0x8e, 0xb6, 0x06, 0x67,
	0xcb, 0x75, 0x2f, 0xfa, 0x58, 0xf7, 0x76, 0xab, 0x57, 0xee, 0xf6, 0x8e, 0x2a, 0x60, 0x9a, 0xfb,
	0x19, 0x1d, 0x65, 0xfe, 0xed, 0xe5, 0x14, 0xd7, 0xdc, 0x28, 0xf3, 0x4f, 0x5f, 0xcf, 0xc7, 0x68,
	0x82, 0x03, 0x72, 0x5d, 0x1a, 0xcd, 0x04, 0xef, 0x71, 0x21, 0xa4, 0xf1, 0x7c, 0x9a, 0xca, 0xd8,
	0x58, 0x25, 0x64, 0x6c, 0xb9, 0x57, 0xd0, 0xde, 0x08, 0x7a, 0xbf, 0xd6, 0xbb, 0xff, 0xf5, 0x4b,
	0x99, 0x70, 0xb1, 0x18, 0x4a, 0xf1, 0xa7, 0xc7, 0x50, 0x8a, 0x49, 0xeb, 0x17, 0x1c, 0x97, 0xde,
	0xa4, 0xe4, 0x06, 0x17, 0xcb, 0x9c, 0xa0, 0x55, 0x4e, 0xd0, 0x67, 0x4e, 0xd0, 0x63, 0x41, 0xa2,
	0x55, 0x41, 0xa2, 0xf7, 0x82, 0x44, 0x37, 0x27, 0x89, 0xf2, 0xb3, 0xfb, 0x29, 0x15, 0xa0, 0x19,
	0x64, 0xa0, 0x17, 0xe1, 0xdf, 0x02, 0x52, 0xf6, 0x33, 0xea, 0x87, 0x30, 0x6c, 0xbf, 0x30, 0xd2,
	0x4d, 0x1b, 0x21, 0x3d, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x82, 0xec, 0xd9, 0x9a, 0x88, 0x01,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AcceptablePriceRatio.Size()
		i -= size
		if _, err := m.AcceptablePriceRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.LimitTotal.Size()
		i -= size
		if _, err := m.LimitTotal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LimitTotal.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.AcceptablePriceRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitTotal", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LimitTotal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptablePriceRatio", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AcceptablePriceRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
