// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reserve/psm/v1/psm.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Stablecoin struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// limit total stablecoin module support
	LimitTotal cosmossdk_io_math.Int       `protobuf:"bytes,2,opt,name=limit_total,json=limitTotal,proto3,customtype=cosmossdk.io/math.Int" json:"limit_total"`
	FeeIn      cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=fee_in,json=feeIn,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_in"`
	FeeOut     cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=fee_out,json=feeOut,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_out"`
}

func (m *Stablecoin) Reset()         { *m = Stablecoin{} }
func (m *Stablecoin) String() string { return proto.CompactTextString(m) }
func (*Stablecoin) ProtoMessage()    {}
func (*Stablecoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_59572214fa05fb2f, []int{0}
}
func (m *Stablecoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stablecoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stablecoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stablecoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stablecoin.Merge(m, src)
}
func (m *Stablecoin) XXX_Size() int {
	return m.Size()
}
func (m *Stablecoin) XXX_DiscardUnknown() {
	xxx_messageInfo_Stablecoin.DiscardUnknown(m)
}

var xxx_messageInfo_Stablecoin proto.InternalMessageInfo

func (m *Stablecoin) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type LockCoin struct {
	Address string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coin    *types.Coin `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Time    int64       `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *LockCoin) Reset()         { *m = LockCoin{} }
func (m *LockCoin) String() string { return proto.CompactTextString(m) }
func (*LockCoin) ProtoMessage()    {}
func (*LockCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_59572214fa05fb2f, []int{1}
}
func (m *LockCoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockCoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockCoin.Merge(m, src)
}
func (m *LockCoin) XXX_Size() int {
	return m.Size()
}
func (m *LockCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_LockCoin.DiscardUnknown(m)
}

var xxx_messageInfo_LockCoin proto.InternalMessageInfo

func (m *LockCoin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LockCoin) GetCoin() *types.Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

func (m *LockCoin) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Stablecoin)(nil), "reserve.psm.v1.Stablecoin")
	proto.RegisterType((*LockCoin)(nil), "reserve.psm.v1.LockCoin")
}

func init() { proto.RegisterFile("reserve/psm/v1/psm.proto", fileDescriptor_59572214fa05fb2f) }

var fileDescriptor_59572214fa05fb2f = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x6b, 0x14, 0x31,
	0x14, 0xc7, 0x67, 0xda, 0x6d, 0xab, 0xa9, 0x08, 0x86, 0x0a, 0xd3, 0x0a, 0xd3, 0xd2, 0x53, 0x11,
	0x9b, 0x38, 0xfa, 0x0d, 0x6a, 0x11, 0x57, 0x0a, 0xe2, 0xe8, 0xc9, 0xcb, 0x92, 0xc9, 0xbc, 0x4e,
	0x43, 0x27, 0x79, 0xcb, 0x24, 0x3b, 0xb8, 0x9f, 0xc1, 0x8b, 0x1f, 0xc3, 0xa3, 0x07, 0x3f, 0x44,
	0x8f, 0xc5, 0x93, 0x78, 0x58, 0x64, 0xf7, 0xe0, 0xd7, 0x90, 0x64, 0xb2, 0x20, 0x78, 0xf3, 0x32,
	0xf3, 0xde, 0xfb, 0x3f, 0x7e, 0x79, 0xf9, 0xe7, 0x91, 0xac, 0x03, 0x0b, 0x5d, 0x0f, 0x7c, 0x6a,
	0x35, 0xef, 0x0b, 0xff, 0x63, 0xd3, 0x0e, 0x1d, 0xd2, 0xfb, 0x51, 0x61, 0xbe, 0xd4, 0x17, 0x07,
	0x7b, 0x0d, 0x36, 0x18, 0x24, 0xee, 0xa3, 0xa1, 0xeb, 0x60, 0x5f, 0xa2, 0xd5, 0x68, 0x27, 0x83,
	0x30, 0x24, 0x51, 0x7a, 0x20, 0xb4, 0x32, 0xc8, 0xc3, 0x37, 0x96, 0xf2, 0xa1, 0x81, 0x57, 0xc2,
	0x02, 0xef, 0x8b, 0x0a, 0x9c, 0x28, 0xb8, 0x44, 0x65, 0x06, 0xfd, 0xf8, 0xd3, 0x06, 0x21, 0xef,
	0x9c, 0xa8, 0x5a, 0xf0, 0x45, 0xba, 0x47, 0xb6, 0x6a, 0x30, 0xa8, 0xb3, 0xf4, 0x28, 0x3d, 0xb9,
	0x5b, 0x0e, 0x09, 0x7d, 0x4b, 0x76, 0x5b, 0xa5, 0x95, 0x9b, 0x38, 0x74, 0xa2, 0xcd, 0x36, 0x8e,
	0xd2, 0x93, 0x7b, 0x67, 0x4f, 0x6f, 0x16, 0x87, 0xc9, 0xcf, 0xc5, 0xe1, 0xc3, 0xe1, 0x04, 0x5b,
	0x5f, 0x33, 0x85, 0x5c, 0x0b, 0x77, 0xc5, 0xc6, 0xc6, 0x7d, 0xff, 0x76, 0x4a, 0xe2, 0x6c, 0x63,
	0xe3, 0xbe, 0xfc, 0xfe, 0xfa, 0x38, 0x2d, 0x49, 0x80, 0xbc, 0xf7, 0x0c, 0xfa, 0x8a, 0x6c, 0x5f,
	0x02, 0x4c, 0x94, 0xc9, 0x36, 0x03, 0xad, 0x88, 0xb4, 0x47, 0xff, 0xd2, 0x2e, 0xa0, 0x11, 0x72,
	0x7e, 0x0e, 0xf2, 0x2f, 0xe6, 0x39, 0xc8, 0x72, 0xeb, 0x12, 0x60, 0x6c, 0xe8, 0x6b, 0xb2, 0xe3,
	0x49, 0x38, 0x73, 0xd9, 0xe8, 0x7f, 0x51, 0x7e, 0x96, 0x37, 0x33, 0x77, 0xdc, 0x90, 0x3b, 0x17,
	0x28, 0xaf, 0x5f, 0x78, 0x2b, 0x32, 0xb2, 0x23, 0xea, 0xba, 0x03, 0x6b, 0xa3, 0x19, 0xeb, 0x94,
	0x9e, 0x92, 0x91, 0x37, 0x2b, 0xf8, 0xb0, 0xfb, 0x6c, 0x9f, 0x45, 0x90, 0xb7, 0x98, 0x45, 0x8b,
	0x99, 0x47, 0x94, 0xa1, 0x8d, 0x52, 0x32, 0x72, 0x4a, 0x43, 0xb8, 0xe8, 0x66, 0x19, 0xe2, 0xb3,
	0x97, 0x37, 0xcb, 0x3c, 0xbd, 0x5d, 0xe6, 0xe9, 0xaf, 0x65, 0x9e, 0x7e, 0x5e, 0xe5, 0xc9, 0xed,
	0x2a, 0x4f, 0x7e, 0xac, 0xf2, 0xe4, 0xc3, 0x93, 0x46, 0xb9, 0xab, 0x59, 0xc5, 0x24, 0x6a, 0x8e,
	0x06, 0xf5, 0x3c, 0xbc, 0x93, 0xc4, 0x96, 0xaf, 0xf7, 0xe6, 0x63, 0xd8, 0x1c, 0x37, 0x9f, 0x82,
	0xad, 0xb6, 0x83, 0xfa, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0xa1, 0xe0, 0x1d, 0x55,
	0x02, 0x00, 0x00,
}

func (m *Stablecoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stablecoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stablecoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FeeOut.Size()
		i -= size
		if _, err := m.FeeOut.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.FeeIn.Size()
		i -= size
		if _, err := m.FeeIn.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.LimitTotal.Size()
		i -= size
		if _, err := m.LimitTotal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintPsm(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LockCoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockCoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockCoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintPsm(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x18
	}
	if m.Coin != nil {
		{
			size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPsm(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintPsm(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPsm(dAtA []byte, offset int, v uint64) int {
	offset -= sovPsm(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Stablecoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovPsm(uint64(l))
	}
	l = m.LimitTotal.Size()
	n += 1 + l + sovPsm(uint64(l))
	l = m.FeeIn.Size()
	n += 1 + l + sovPsm(uint64(l))
	l = m.FeeOut.Size()
	n += 1 + l + sovPsm(uint64(l))
	return n
}

func (m *LockCoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovPsm(uint64(l))
	}
	if m.Coin != nil {
		l = m.Coin.Size()
		n += 1 + l + sovPsm(uint64(l))
	}
	if m.Time != 0 {
		n += 1 + sovPsm(uint64(m.Time))
	}
	return n
}

func sovPsm(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPsm(x uint64) (n int) {
	return sovPsm(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Stablecoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stablecoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stablecoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitTotal", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPsm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LimitTotal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeIn", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPsm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeIn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeOut", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPsm
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeOut.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LockCoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LockCoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LockCoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPsm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Coin == nil {
				m.Coin = &types.Coin{}
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPsm(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPsm
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPsm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPsm
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPsm
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPsm
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPsm        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPsm          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPsm = fmt.Errorf("proto: unexpected end of group")
)
